pull_request_title: "fix: new Crowdin updates"
commit_message: "fix: new translations %original_file_name% from Crowdin"
files:
  - source: /plugnmeet/languages/plugnmeet.pot
    translation: /plugnmeet/languages/%file_name%-%locale_with_underscore%.po
