name: Generate Translations
on:
  push:
    branches:
      - l10n_main

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - name: Build project
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          php wp-cli.phar i18n make-mo ./plugnmeet/languages/
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          branch: ${{ github.head_ref }}
          force: true
          message: "generated .mo files"
          github_token: ${{ secrets.GITHUB_TOKEN }}
